### ISSUE TITLE
Make reCAPTCHA work globally

### ISSUE THREAD

**Issue by tr-lewis** [sutjin/google-recaptcha-react-component#6]
Thank you for creating such a simple to use and clean library. I have been using it in my personal projects and found that it works well for the most part. 

Recently I noticed that some customers from China are getting errors when they try to use my site and I discovered the it is because of the ```RECAPTCHA_URL``` in loader.js.

According to the link below:

* https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

It can be solved by using "www.recaptcha.net" in your code in circumstances when "www.google.com" is not accessible.

*    First, replace <script src="https://www.google.com/recaptcha/api.js" async defer></script> with <script src="https://www.recaptcha.net/recaptcha/api.js" async defer></script>

**Comment by sutjin** [comment]
Hi

I fixed the issue in version 3.0 by introducing a flag to indicate if you want to use the secondary endpoint or not
